[package]
name = "dungeoncrawl"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand = "2.3.0"
input_lib = { version = "0.1.0", path = "../input_lib" }
macroquad = "0.4.14"
getrandom = { version = "*", features = ["js"] }
bevy_ecs = "0.16.0"
strum = "0.27.1"
strum_macros = "0.27.1"
